### ISSUE TITLE
can I use branch 12.0 in android 13version?

### ISSUE THREAD

**Issue by hhhaiai** [crdroidandroid/android_vendor_xiaomi_cepheus#1]
rt

**Comment by hhhaiai** [comment]
@gwolf2u  why close??

**Comment by gwolf2u** [comment]
Because this is not an issue

**Comment by hhhaiai** [comment]
hi, brother, this library only has 12.0 branches. Can I use this library in the Android 13 version?  @gwolf2u

**Comment by gwolf2u** [comment]
no can not
